# Generated by Django 4.1 on 2022-09-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'app_user',
                'managed': False,
            },
        ),
    ]
